spring:
  profiles:
    active:
     -dev

------
spring:       #开发环境
  profiles: dev
  application:
         name: microserviceclound-config-mdc-dev



------
spring:
  profiles: test	#测试环境
  application:
         name: microserviceclound-config-mdc-test
