spring: 
  profiles:
    active:
    - dev

    
--- 
spring: 
  profiles: dev
  application:
    name: microserviceclound-mdc-dev


---
spring: 
  profiles: test
  application:
    name: microserviceclound-mdc-test








  
